### ISSUE TITLE
Bug: "Get Started" button does not submit user

### ISSUE THREAD

**Issue by tomshomelab** [cmintey/wishlist#161]
**Describe the bug**
After a fresh deployment my credentials for administrator sign up will not submit. The "get started" button does nothing. The animation plays a little for clicking the button but no action or feedback on the screen. 

I have made sure the passwords match, they have a special character, a captical letter, some numbers and letters and is between 8 - 12 characters long. 

*EDIT* I initally added the IPV4 address of the VM running the application to the `ORIGIN` environment variable and then replaced this with my domain when the submit button didnt work. 

Connecting to the domain i have gives an SSL error. The domain reads "ssd handshake fails"

**To Reproduce**
1. deply docker compose
2. enter creds for new user
3. press get started

**Expected behavior**
i expect to be able to press get started after entering my credentials and have my account created

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 24.4
 - Docker compose deployment

**Comment by cmintey** [comment]
Make sure the `ORIGIN` environment variable is set and is the same base url as your are connecting to

**Comment by tomshomelab** [comment]
> Make sure the `ORIGIN` environment variable is set and is the same base url as your are connecting to

Hi thanks for replying. 

ive added first the IPV4 which is when i first faced the issue. Then i tested domain which gave me the SSL cert issue

**Comment by cmintey** [comment]
I don't think the SSL cert issue would be related to Wishlist. Are you using a reverse proxy? Do you have any logs?

**Comment by tomshomelab** [comment]
> I don't think the SSL cert issue would be related to Wishlist. Are you using a reverse proxy? Do you have any logs?

okay - lets focus on the IPV4 address submit button not working. 

I was using nginx reverse proxy with cloudflare. There were no errors in ngixn reverse proxy, here is an attached log file from wish list
[_wishlist_logs.txt](https://github.com/user-attachments/files/17689476/_wishlist_logs.txt)

**Comment by cmintey** [comment]
Any logs in the browser? In your ORIGIN env var, are you including the port?

**Comment by tomshomelab** [comment]
> Any logs in the browser? In your ORIGIN env var, are you including the port?

im not sure how to check logs in my browser. I tried the local IPV4 page with port on edge, firefox, opera and incogneto mode on all with the same "submit" button not submitting issue. 

for the ORIGIN env var i did not include the port within the IPV4 or domain.

**Comment by cmintey** [comment]
Add the port to ORIGIN if you're using the ip. `ORIGIN=http://<ip>:<port>`. Port shouldn't be necessary if you're using your domain, unless the port is different than 443

**Comment by tomshomelab** [comment]
but without the port in the ip range for IPV4 i can access the page and enter information. I dont think a port missing would cause this issue. 

adding the port for IPV4 and domain fixed neither issues. submit button is still busted and there is an SSL issue witht using domain.

**Comment by cmintey** [comment]
The port matters not for accessing the page, but for form submissions. To verify, when you land on the mealie page, right click anywhere on the page and click "Inspect". This is the browser dev tools. Here you can view the Console where you can see logs, and also the Network tab. Let me know what you see in here when clicking the buttom

Also can you share your docker-compose and env file (if applicable)?

**Comment by tomshomelab** [comment]
toggling on the inspect screen and being in the console allowed me to press submit.. why would that be the case? there were no errors in the console feed. 

below is my docker compose. i have been switching between env options by using the # to remove them im currently connected via IPV4. 

```
services:
  wishlist:
    container_name: wishlist
    image: ghcr.io/cmintey/wishlist:latest
    ports:
      - 3280:3280
    volumes:
      - /docker/wishlist/uploads:/usr/src/app/uploads  # This is where user image uploads will be stored
      - /docker/wishlist/data:/usr/src/app/data        # This is where the sqlite database will be stored
    environment:
      ORIGIN: http://192.168.0.82:3280 # The URL users will connect to
      #ORIGIN: https://wishlist.WEBSITE:3280 # The URL users will connect to
      TOKEN_TIME: 72 # hours until signup and password reset tokens expire
```
